# Generated by Django 5.1.7 on 2025-03-28 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_alter_usuario_data_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_filme', models.CharField(max_length=50)),
                ('ano_de_lancamento', models.CharField(max_length=50)),
                ('estudio', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('sinopse', models.CharField(max_length=50)),
                ('data_de_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_de_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
