# Generated by Django 5.1.7 on 2025-03-31 17:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_filme_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='ano_de_lancamento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='filme',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.genero'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='sinopse',
            field=models.TextField(),
        ),
    ]
